# Generated by Django 5.0.4 on 2024-04-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tarea', models.CharField(max_length=20)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_entrega', models.DateField(null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('materia', models.ManyToManyField(related_name='tareas', to='materias.materia')),
            ],
        ),
    ]
