# Generated by Django 5.0.4 on 2024-04-29 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_tarea'),
        ('usuarios', '0003_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id_tipo_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_archivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='estudiante',
            field=models.ManyToManyField(related_name='inscripcion', to='usuarios.student'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='carreras',
            field=models.ManyToManyField(related_name='materia_carrera', to='materias.carrera'),
        ),
        migrations.RemoveField(
            model_name='materia',
            name='docente',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='materia',
            field=models.ManyToManyField(related_name='tarea_materia', to='materias.materia'),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('retraso_entrega', models.DateField()),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('archivo', models.BinaryField(null=True)),
                ('tarea', models.ManyToManyField(related_name='tarea_entrega', to='materias.tarea')),
                ('tipo_archivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materias.tipoarchivo')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='docente',
            field=models.ManyToManyField(related_name='docente_materia', to='usuarios.teacher'),
        ),
    ]
